name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Vim
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y libncurses5-dev libgnome2-dev libgnomeui-dev \
            libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
            libcairo2-dev libx11-dev libxpm-dev libxt-dev \
            python3-dev
        mkdir -p ~/src
        git clone https://github.com/vim/vim.git ~/src/vim
        cd ~/src/vim
        ./configure --with-features=huge \
                  --enable-multibyte \
                  --enable-python3interp=yes \
                  --enable-gui=gtk2 \
                  --enable-cscope \
                  --prefix=/usr/local
         make -j$(nproc)
         sudo make install
    - name: Install dependencies
      run: |
        sudo apt-get install -y clang-tools-8
        sudo update-alternatives --install /usr/bin/clangd clangd $(which clangd-8) 100
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        ln -sf $(pwd)/test/vimrc ~/.vim/vimrc
        vim +PlugInstall +qall
    - name: Print versions
      run: |
        vim --version
        clangd --version
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
    - name: Run tests
      run: |
        cd test/
        vim -S clangd.vim
        cat test.log
