name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v1
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y vim clang-tools-8
        sudo update-alternatives --install /usr/bin/clangd clangd $(which clangd-8) 100
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        ln -sf $(pwd)/test/vimrc ~/.vim/vimrc
        vim +PlugInstall +qall
    - name: Print versions
      run: |
        vim --version
        clangd --version
    - name: Run tests
      run: |
        cd test/
        vim -S clangd.vim
        cat test.log
